// Generated by Classiq.
// Classiq version: 0.49.0
// Creation timestamp: 2024-09-23T16:15:32.187022+00:00
// Random seed: 83561829

OPENQASM 2.0;
include "qelib1.inc";
gate mcx_hybrid_gray_code_maslov15 q0,q1 {
  cx q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_o0 q0,q1 {
  x q0;
  mcx_hybrid_gray_code_maslov15 q0,q1;
  x q0;
}

gate statepreparation_0_rygate_1_mcx_0 q0,q1 {
  mcx_hybrid_gray_code_maslov15_o0 q0,q1;
}

gate statepreparation_0_rygate_1 q0,q1 {
  statepreparation_0_rygate_1_mcx_0 q1,q0;
  ry(-0.6154797086703874) q0;
  statepreparation_0_rygate_1_mcx_0 q1,q0;
  ry(0.6154797086703874) q0;
}

gate main_statepreparation_0 q0,q1 {
  ry(pi/3) q1;
  statepreparation_0_rygate_1 q0,q1;
}

gate lcu_controllers_inplace_prepare_int_0 q0,q1 {
  x q0;
  x q1;
}

gate ccapply_to_all_expanded___5 q0,q1,q2,q3 {
}

gate lcu_controllers_apply_to_all q0,q1,q2,q3 {
  ccapply_to_all_expanded___5 q0,q1,q2,q3;
}

gate lcu_controllers_inplace_prepare_int_1 q0,q1 {
  x q1;
  x q0;
}

gate lcu_controllers_inplace_prepare_int_2 q0,q1 {
  x q1;
}

gate mcx q0,q1,q2,q3 {
  h q3;
  p(pi/8) q0;
  p(pi/8) q1;
  p(pi/8) q2;
  p(pi/8) q3;
  cx q0,q1;
  p(-pi/8) q1;
  cx q0,q1;
  cx q1,q2;
  p(-pi/8) q2;
  cx q0,q2;
  p(pi/8) q2;
  cx q1,q2;
  p(-pi/8) q2;
  cx q0,q2;
  cx q2,q3;
  p(-pi/8) q3;
  cx q1,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q0,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q1,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q0,q3;
  h q3;
}

gate ccswap q0,q1,q2,q3 {
  mcx q0,q1,q2,q3;
  mcx q0,q1,q3,q2;
  mcx q0,q1,q2,q3;
}

gate mcphase(param0) q0,q1,q2 {
  cp(pi/2) q1,q2;
  cx q1,q0;
  cp(-pi/2) q0,q2;
  cx q1,q0;
  cp(pi/2) q0,q2;
}

gate mcphase_140678787930384(param0) q0,q1,q2 {
  cp(0) q1,q2;
  cx q1,q0;
  cp(0) q0,q2;
  cx q1,q0;
  cp(0) q0,q2;
}

gate cch q0,q1,q2 {
  mcphase(pi) q0,q1,q2;
  ry(pi/4) q2;
  ccx q0,q1,q2;
  ry(-pi/4) q2;
  ccx q0,q1,q2;
  mcphase_140678787930384(0) q0,q1,q2;
}

gate mcphase_140678787936016(param0) q0,q1,q2,q3 {
  cp(pi/8) q2,q3;
  cx q2,q1;
  cp(-pi/8) q1,q3;
  cx q2,q1;
  cp(pi/8) q1,q3;
  cx q1,q0;
  cp(-pi/8) q0,q3;
  cx q2,q0;
  cp(pi/8) q0,q3;
  cx q1,q0;
  cp(-pi/8) q0,q3;
  cx q2,q0;
  cp(pi/8) q0,q3;
}

gate cciteration_expanded___10 q0,q1,q2,q3 {
  cch q0,q1,q2;
  mcphase_140678787936016(pi/2) q0,q1,q3,q2;
}

gate ccqft_no_swap_expanded___12 q0,q1,q2,q3 {
  cciteration_expanded___10 q0,q1,q2,q3;
  cch q0,q1,q3;
}

gate ccqft_expanded___13 q0,q1,q2,q3 {
  ccswap q0,q1,q2,q3;
  ccqft_no_swap_expanded___12 q0,q1,q2,q3;
}

gate lcu_controllers_qft_0 q0,q1,q2,q3 {
  ccqft_expanded___13 q0,q1,q2,q3;
}

gate lcu_controllers_inplace_prepare_int_3 q0,q1 {
  x q1;
}

gate lcu_controllers_inplace_prepare_int_4 q0,q1 {
  x q0;
}

gate mcphase_140678504540304(param0) q0,q1,q2,q3 {
  cp(-pi/8) q2,q3;
  cx q2,q1;
  cp(pi/8) q1,q3;
  cx q2,q1;
  cp(-pi/8) q1,q3;
  cx q1,q0;
  cp(pi/8) q0,q3;
  cx q2,q0;
  cp(-pi/8) q0,q3;
  cx q1,q0;
  cp(pi/8) q0,q3;
  cx q2,q0;
  cp(-pi/8) q0,q3;
}

gate cciteration_expanded___18_dg q0,q1,q2,q3 {
  mcphase_140678504540304(-pi/2) q0,q1,q3,q2;
  cch q0,q1,q2;
}

gate ccqft_no_swap_expanded___20_dg q0,q1,q2,q3 {
  cch q0,q1,q3;
  cciteration_expanded___18_dg q0,q1,q2,q3;
}

gate ccqft_expanded___21_dg q0,q1,q2,q3 {
  ccqft_no_swap_expanded___20_dg q0,q1,q2,q3;
  ccswap q0,q1,q2,q3;
}

gate lcu_controllers_qft_1 q0,q1,q2,q3 {
  ccqft_expanded___21_dg q0,q1,q2,q3;
}

gate lcu_controllers_inplace_prepare_int_5 q0,q1 {
  x q0;
}

gate main_lcu_controllers q0,q1,q2,q3 {
  lcu_controllers_inplace_prepare_int_0 q2,q3;
  lcu_controllers_apply_to_all q2,q3,q0,q1;
  lcu_controllers_inplace_prepare_int_1 q2,q3;
  lcu_controllers_inplace_prepare_int_2 q2,q3;
  lcu_controllers_qft_0 q2,q3,q0,q1;
  lcu_controllers_inplace_prepare_int_3 q2,q3;
  lcu_controllers_inplace_prepare_int_4 q2,q3;
  lcu_controllers_qft_1 q2,q3,q0,q1;
  lcu_controllers_inplace_prepare_int_5 q2,q3;
}

gate statepreparation_1_rygate_0_qinverse_mcx_0_qinverse q0,q1 {
  mcx_hybrid_gray_code_maslov15_o0 q0,q1;
}

gate statepreparation_1_rygate_0_qinverse_mcx_1_qinverse q0,q1 {
  mcx_hybrid_gray_code_maslov15_o0 q0,q1;
}

gate statepreparation_1_rygate_0_qinverse q0,q1 {
  ry(-0.6154797086703874) q0;
  statepreparation_1_rygate_0_qinverse_mcx_0_qinverse q1,q0;
  ry(0.6154797086703874) q0;
  statepreparation_1_rygate_0_qinverse_mcx_1_qinverse q1,q0;
}

gate main_statepreparation_1 q0,q1 {
  statepreparation_1_rygate_0_qinverse q0,q1;
  ry(-pi/3) q1;
}

qreg q[4];
main_statepreparation_0 q[2],q[3];
main_lcu_controllers q[0],q[1],q[2],q[3];
main_statepreparation_1 q[2],q[3];
